Introduce svg-to-compose Gradle Plugin (#83)
* feat: add initial gradle plugin definition

* chore: decouple sample-app from parent project
refactor: rename sample-app to playground

* feat: add exclude regex

* feat: add icon name mapper function

* chore: change sourceSrc for output files

* feat: add kmp preview support

* fix: rgb color parse to compose color

* feat: ensure icon name is created based on input filename when output is a directory

* feat: add plugin caching

* feat: improve plugin performance and configuration

- Improves plugin performance by implementing a persistent cache to store file hashes and plugin configurations.
- Introduces structured DSL with new configuration blocks for more flexibility and error validation.
- Improves the configuration structure to use properties for lazy evaluation and better control over icon generation parameters.
- Refactors file handling to use `java.nio.file.Path` for enhanced cross-platform support.

* perf: enable parallel icons processing

* chore: move ProcessorConfiguration out of internal package

* feat: introduced Logger interface for better logging on gradle plugin

* refactor: use FileManager to manage file operations
refactor: move cache logic to CacheManager
refactor: use dependency injection on gradle plugin

* feat: add support for common configuration

* chore: adopt Kotlin script convention plugins for project configuration

* fix: address lint issues

* fix: convert empty value to float

* refactor: optimize temporary files creation for parallel execution

* refactor: optimize cache creation for parallel execution

* chore: update playground project to use new plugin api

* chore: use coroutines to run parallel icon parsing
refactor: enhance error handling and reporting during icon parsing.
chore: add more detailed logging with debug and verbose options.

* chore: gradle plugin logger improvements

* refactor: use logger interface on Optimizer
chore: error handling improvement on Optimizer

* fix: using wrong object on flatmap

* chore: enhance error handling

* refactor: improve dependency injection

- Improve type safety and error handling in dependency injection.
- Refactor FileManager dependency to be injected directly.

* chore: move processor.dispose call to task's dispose method

* refactor: use substringBeforeLast instead
doc: add ktdoc to FileManager.readBytes

* refactor: enhance app.properties reading
refactor: improve detekt configurations

* chore: upgrade gradlew wrapper

* refactor: simplify exclude logic

* refactor: move from Companion to proper Factory class

* refactor: run task action in coroutine scope

Run the `ParseSvgToComposeIconTask` action within a coroutine scope using `runBlocking`.
This change ensures that the task's operations, including file processing and cache management, are executed within a structured concurrency context.
Additionally, it allows for proper disposal of resources by invoking `processor.dispose()` in a `finally` block to ensure cleanup even in case of exceptions.

* refactor: enhance caching mechanism

Improve caching by storing output file paths and handling deleted origin files.
- Include output file paths in the cache data to track generated files.
- Detect and delete generated files when corresponding origin files are deleted.
- Handle cache serial version changes by removing the cache.
- Refactor file system operations for improved modularity.
- Enhance logging for cache operations.

* feat: enable experimental parallel processing

This commit introduces experimental parallel processing for icon conversion.

It allows users to configure the maximum number of threads used for parallel processing, which can significantly reduce the conversion time for large projects with many icons.

The feature is marked as experimental and requires an opt-in using the `@ExperimentalParallelProcessing` annotation.

* chore: enhance error handling on Android projects

* feat: add persistent code generation

* chore: add ticket number to todos

* docs: add dokka to project

* chore: prepare for 2.0.0-rc01 release

- Adds maven publishing configuration for both the library and the Gradle plugin.
- Updates the version in `app.properties` to `2.0.0-rc01`.
- Adds necessary metadata to the POM files, including project description, licenses, developers, and SCM information.
- Configures publishing to Maven Central using the SonatypeHost.CENTRAL_PORTAL.
- Adds signing for all publications.
- Makes the `main` function in `Main.kt` private, as it's only for debugging purposes.
- Refactors project properties into a dedicated class.

* docs: add gradle plugin docs

* chore: update integrity check script

* chore: add parallelism verification

* chore: downgrade to dokka 1.9.20

With dokka 2.0.0-Beta, the Gradle Plugin stopped to sync. The error was caused by: java.lang.NoClassDefFoundError: dev/tonholo/s2c/error/ExitProgramException.

I'm unsure why that happened, it appears that dokka was removing classes from the jar file generated by the KMP.

If dokka is applied only in the Gradle Plugin, the error doesn't happen, however when applied in the KMP library, it does.

* chore: merge duplicated md section

* chore: update required property message

* chore: improve hash calculation and validation

* chore: improve logger

* fix: root playground android app path

* chore: revert must create on temp directory

* feat: add exclude regex option to CLI

* fix: build task dependencies

* feat: add icon's name replace option to CLI

* chore: add s2c name to help text

* docs: update CLI and Gradle plugin docs

* chore: change deprecated implementation to use logger instead

* chore: move hardcoded values to constants

* chore: suppress info log when silent is enabled

* chore: add playground kmp project

* chore: add comparison between AS generated vs plugin generated on the playground app
chore: renamed package svgToCompose to svg_to_compose

* docs: add merged documentation on root folder
docs: add documentation for each project

* docs: fix typo

* docs: fix doc format

* fix: use snake case instead of camel case for package naming